name: saksham
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.3
  http: ^1.2.0
  provider: ^6.1.2
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  flutter_localizations:
    sdk: flutter
  socket_io_client: ^3.0.1
  fl_chart: ^0.70.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/launcher/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#4A90E2"
  adaptive_icon_foreground: "assets/launcher/icon.png"

fonts:
  - family: Lexend
    fonts:
      - asset: assets/fonts/Lexend-Regular.ttf
      - asset: assets/fonts/Lexend-Bold.ttf
        weight: 700

flutter:
  generate: true
  uses-material-design: true
